// <auto-generated />
using System;
using EindCaseBackEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EindCaseBackEnd.Migrations
{
    [DbContext(typeof(CursusContext))]
    partial class CursusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EindCaseBackEnd.Models.Cursus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Duur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Cursussen");
                });

            modelBuilder.Entity("EindCaseBackEnd.Models.CursusInstantie", b =>
                {
                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CursusCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StartDatum", "Code");

                    b.HasIndex("CursusCode");

                    b.ToTable("CursusInstanties");
                });

            modelBuilder.Entity("EindCaseBackEnd.Models.CursusInstantie", b =>
                {
                    b.HasOne("EindCaseBackEnd.Models.Cursus", "Cursus")
                        .WithMany("CursusInstanties")
                        .HasForeignKey("CursusCode");

                    b.Navigation("Cursus");
                });

            modelBuilder.Entity("EindCaseBackEnd.Models.Cursus", b =>
                {
                    b.Navigation("CursusInstanties");
                });
#pragma warning restore 612, 618
        }
    }
}
